export default function MethodologyPage() {
  return (
    <main className="page-shell">
      <div className="container">
        <div className="page-head">
          <div>
            <div className="tech-label page-kicker"><span className="pulse-dot" /> METHODOLOGY</div>
            <h1 className="page-title">Rule-based<br />agent risk.</h1>
            <p className="page-desc">A-DAP-T keeps the security verdict deterministic. Gemini explains results only after rule-based scanning has produced findings, severity, scores, patches, and gate decisions.</p>
          </div>
        </div>
        <section className="grid grid-3">
          {[
            ['Scanner decides', 'Findings, severity, category scores, safety score, attack paths, patch previews, and deployment gate decisions are generated by deterministic backend logic.'],
            ['Gemini explains', 'Gemini is used only for compact summaries, next steps, remediation wording, and DAP answers grounded in the report.'],
            ['No code execution', 'GitHub repositories and ZIP files are read as text under safe extraction limits. Uploaded or downloaded project code is never executed.'],
          ].map(([title, body]) => (
            <article className="glass-card panel shimmer" key={title}>
              <div className="panel-label">CONTROL</div>
              <h2 className="panel-title">{title}</h2>
              <p className="muted">{body}</p>
            </article>
          ))}
        </section>
      </div>
    </main>
  );
}
